mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
]

polls/urls.py
from django.urls import path, re_path
from django.views.generic.base import RedirectView

from . import views

favicon_view = RedirectView.as_view(url='/static/polls/linux.ico', permanent=True)

app_name = 'polls'
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    re_path(r'^favicon\.ico$', favicon_view),
    # 5/
    path('<int:pk>/', views.Details.as_view(), name='details'),
    # 5/vote
    path('<int:question_id>/vote', views.vote, name='vote'),
    # 5/results
    path('<int:pk>/results', views.Results.as_view(), name='results'),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    q_text = models.CharField(max_length=200)
    publish_date = models.DateTimeField('date published')
    def __str__(self):
        return self.q_text
    def was_published_recently(self):
        now = timezone.now()
        return now >= self.publish_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice
'''
def index(request):
    latest_question_list = Question.objects.order_by('-publish_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)
'''
class Index(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(publish_date__lte=timezone.now()
                                      ).order_by('-publish_date')[:5]

'''
def details(request, question_id):
    q = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/details.html', {'question': q})
    
def results(request, question_id):
    q = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': q})
'''
class Details(generic.DetailView):
    template_name = 'polls/details.html'

    def get_queryset(self):
        return Question.objects.filter(publish_date__lte=timezone.now())

class Results(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    q = get_object_or_404(Question, pk=question_id)
    try:
        voted_choice = q.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/details.html', {
                'question': q,
                'error_msg': "Invalid Choice"})
    else:
        voted_choice.votes += 1
        voted_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(q.id, )))

polls/templates/polls/details.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Details</title>
  </head>
  <body>
    <h1>{{ question.q_text }}</h1>

    {% if error_msg %}<p><strong>{{ error_msg }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
      {% csrf_token %}
      {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
      {% endfor %}
      <input type="submit" value="Vote">
    </form>
  </body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <title>Polls</title>
  </head>
  <body>
	{% if latest_question_list %}
		<ul>
		{% for question in latest_question_list %}
			<li><a href="{% url 'polls:details' question.id %}">{{ question.q_text }}</a></li>
		{% endfor %}
		</ul>
	{% else %}
		<p>No polls are available.</p>
	{% endif %}
  </body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Result</title>
  </head>
  <body>
    <h1>{{ question.q_text }}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'polls:details' question.id %}">Vote again?</a>
  </body>
</html>